[project]
name = "etl-2"
version = "0.1.0"
description = ""
requires-python = ">=3.10,<4.0"

dependencies = [
    "fastapi==0.95.2",
    "uvicorn[standard]==0.22.0",
]

[tool.uv]
dev-dependencies = [
    "pipdeptree==2.26.1",
]